version: '3.9'
name: 'schedulify'

# Configurations shared between api service, celery and celery beat.
x-base-api: &base-api
  env_file:
    - ../api/.env
  volumes:
    - ../api:/opt/api
  build:
    context: ..
    dockerfile: docker/images/api/Dockerfile
    target: local

services:
  api:
    <<: *base-api
    command: ["make", "run"]
    depends_on:
      - postgres-db
      - redis-db
    ports:
      - ${LOCAL_IP:-127.0.0.1}:${API_LOCAL_PORT:-8000}:8000

  celery-worker:
    <<: *base-api
    command: ["make", "celery-worker-run"]
    depends_on:
      - api
      - redis-db

  celery-beat:
    <<: *base-api
    command: ["make", "celery-beat-run"]
    depends_on:
      - api
      - redis-db

  postgres-db:
    platform: linux/amd64
    environment:
      POSTGRES_USER: schedulify_user
      POSTGRES_DB: schedulify_db
      POSTGRES_PASSWORD: schedulify_password
    image: postgis/postgis
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data:rw

  redis-db:
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data:rw

volumes:
  pg_data: {}
  redis_data: {}
