# Generated by Django 4.2.11 on 2024-05-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_team"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="teams",
            field=models.ManyToManyField(blank=True, default=[], related_name="events", to="accounts.team"),
        ),
    ]
